#!/bin/env bash
colors_path=$HOME/.cache/wal/colors.sh

memory_usage=$(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)

if [ -f "$colors_path" ]; then
  source $colors_path
  echo "^b$color1^^c$color0^  ^d^^b$color8^^c$color0^ $memory_usage ^d^"
fi
