#!/bin/env bash
colors_path=$HOME/.cache/wal/colors.sh

memory_usage=$(free -h | awk '/^Mem/ { print $3 }' | sed s/i//g)


cpu_usage=$(top -bn1 | grep "Cpu(s)" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print 100 - $1"%"}')
cpu_usage=$(printf "%.0f" "$cpu_usage")

if [ -f "$colors_path" ]; then
  source $colors_path
  echo "^b$color2^^c$color0^  $memory_usage ^d^^b$color8^^c$color0^  $cpu_usage% ^d^"
fi
